version: "3"
name: shopping-cart-ms

services:
  app:
    container_name: shopping-cart-api
    image: shopping-cart-api    # docker build -t shopping-cart-api .
    ports:                      
      - 80:80                   
      - 443:443                 
    
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminn
      - MONGO_INITDB_ROOT_PASSWORD=passwordd
    volumes:
      - mongodb-data:/data/db
    
volumes:
  mongodb-data:
    driver: local