version: "3"
name: shopping-cart-ms
services:
  app:
    container_name: shopping-cart-api
    image: shopping-cart-api    # docker build -t shopping-cart-api .
    ports:                      
      - 80:80                   
      - 443:443                 
    
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminn
      - MONGO_INITDB_ROOT_PASSWORD=passwordd
    volumes:
      - mongodb-data:/data/db
    
  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    ports:
        - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=adminn
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passwordd
      - ME_CONFIG_MONGODB_SERVER=mongodb 
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local